### ISSUE TITLE
Does not work with mongoose 4.4.7

### ISSUE THREAD

**Issue by richardlay** [OptimalBits/node_acl#179]
Hi, I'm using acl 0.4.9 and mongoose 4.4.7 (latest at the time of writing).

When using the acl 'allow' method I get an empty error object in the callback, and sometimes also the following stack trace. Mongoose 4.4.6 is fine.

```
Parameter mismatch.
Input:
( users: string, undefined: undefined, function (err, value) {
        if (promise === null) return;

        if (err) {
            var wrapped = wrapAsOperationalError(maybeWrapAsError(err));
            promise._attachExtraTrace(wrapped);
            promise._reject(wrapped);
        } else if (arguments.length > 2) {
            var $_len = arguments.length;var args = new Array($_len - 1); for(var $_i = 1; $_i < $_len; ++$_i) {args[$_i - 1] = arguments[$_i];}
            promise._fulfill(args);
        } else {
            promise._fulfill(value);
        }

        promise = null;
    }: function)
Accepted:
(string, string|number, function)
```

**Comment by jsec516** [comment]
It worked for me (mongoose ^4.4.7, acl ^0.4.9)

var mongoose = require('mongoose'),
	Acl = require('acl');
mongoose.connect('mongodb://127.0.0.1:27017/test', function(err) {
    if (err) throw err;
    
});

mongoose.connection.on('connected', function () {  
  authorization_setup(null, mongoose.connection.db);
}); 
function authorization_setup( error, db ) {

    var mongoBackend = new Acl.mongodbBackend( db, 'acl_' );
    var acl = new Acl( mongoBackend);

    acl.allow([
        {
            roles: 'admin',
            allows: [
                { resources: '/secret', permissions: '*' },
                { resources: '/blog', permissions: '*' }
            ]
        }, {
            roles: 'user',
            allows: [
                { resources: '/secret', permissions: 'get' }
            ]
        }, {
            roles: 'guest',
            allows: []
        }
    ]);

    acl.addRoleParents( 'user', 'guest' );
    acl.addRoleParents( 'admin', 'user' );
    acl.removeUserRoles( 'joed', 'admin', function(err) {console.log('removed admin role');})
    acl.addUserRoles('joed', 'user');
    // acl.addUserRoles('joed', 'user');

    acl.hasRole( 'joed', 'admin', function(err, hasRole) {
    	console.log(hasRole);
    });

    acl.hasRole( 'joed', 'user', function(err, hasRole) {
    	console.log(hasRole);
    });

    acl.isAllowed('joed', '/secret', 'get', function(err, allowed){
    	console.log('secret/get is ', allowed);
    });
}

**Comment by richardlay** [comment]
@jsec516 which version of mongo database are you using?

**Comment by richardlay** [comment]
I've upgraded to 4.4.8 and it's fixed.

For reference here was the issue that was causing my issue:
https://github.com/Automattic/mongoose/issues/3972

Nothing to do with ACL, but stemmed from having to pass the db object into ACL.
